name: Build and push Docker images

on:
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontChess
          file: ./frontChess/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/42chess-frontend:latest
            ghcr.io/${{ github.repository_owner }}/42chess-frontend:${{ github.sha }}
          build-args: |
            VITE_API_URL=${{ secrets.VITE_API_URL }}

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backChess
          file: ./backChess/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/42chess-backend:latest
            ghcr.io/${{ github.repository_owner }}/42chess-backend:${{ github.sha }}
          build-args: |
            # If you need to pass build-time args to the backend, add them here
            # E.g. SOME_BUILD_ARG=${{ secrets.SOME_BUILD_ARG }}

      - name: Output image names
        run: |
          echo "Frontend image: ghcr.io/${{ github.repository_owner }}/42chess-frontend:latest"
          echo "Backend image:  ghcr.io/${{ github.repository_owner }}/42chess-backend:latest"
